[build]
target = "x86_64-arc-os.json"
rustflags = ["-Zunstable-options"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[env]
RUSTC = { value = "C:\\Users\\Arda\\source\\repos\\arc-os\\rustc.bat" }
